In [13]:
from numba import cuda, float32
import math

In [14]:
import numpy as np

def square_matrix(size, *elements):
    return np.array(elements).reshape(size, size)

a= square_matrix(3,[2,3,4,2,1,2,3,4,1])
b= square_matrix(3,[2,3,4,2,1,2,3,4,1])
c= square_matrix(3,[0,0,0,0,0,0,0,0,0])

#a=[[1,2,3,1,2,3,1,2,3]]
# a=[[1,2,3],[1,2,3],[1,2,3]]
# b=[[1,2,3],[1,2,3],[1,2,3]]
# c=[[0,0,0],[0,0,0],[0,0,0]]

In [15]:
@cuda.jit
def matmul(A, B, C):
    """Perform square matrix multiplication of C = A * B
    """
    i, j = cuda.grid(2)
    if i < C.shape[0] and j < C.shape[1]:
        tmp = 0.
        for k in range(A.shape[1]):
            tmp += A[i, k] * B[k, j]
        C[i, j] = tmp


In [16]:
threadsperblock = (7, 7)
blockspergrid_x = math.ceil(a.shape[0] / threadsperblock[0])
blockspergrid_y = math.ceil(a.shape[1] / threadsperblock[1])
blockspergrid = (blockspergrid_x, blockspergrid_y)
matmul[blockspergrid, threadsperblock](a,b,c)

print(c)

[[22 25 18]
 [12 15 12]
 [17 17 21]]
